spring:
  application:
    name: auth-service
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5003/auth_db}
    username: ${AUTH_SERVICE_DB_USER:admin_user}
    password: ${AUTH_SERVICE_DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate

auth:
  security:
    lockout:
      max-attempts: 5
      lock-duration: 15m
      quiet-window: 1h
  jwt:
    access-token-ttl: 15m

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 4003

logging:
  level:
    root: INFO
