services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_USER: ${PATIENT_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${PATIENT_SERVICE_DB_PASSWORD}
      POSTGRES_DB: ${PATIENT_SERVICE_DB_NAME}
    ports:
      - "5000:5432"
    volumes:
      - patient-service-db-data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PATIENT_SERVICE_DB_USER} -d ${PATIENT_SERVICE_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    image: patient-service:latest
    container_name: patient-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/${PATIENT_SERVICE_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${PATIENT_SERVICE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${PATIENT_SERVICE_DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    ports:
      - "4000:4000"
    networks:
      - internal
    depends_on:
      patient-service-db:
        condition: service_healthy
    
volumes:
  patient-service-db-data:

networks:
  internal:
    driver: bridge
