### POST request to create a patient
@baseUrl = http://localhost:4000/api/v1

POST {{baseUrl}}/patients
Content-Type: application/json

{
  "name": "Tiwa Tope",
  "email": "tiwa@example.com",
  "address": "123 Java Boot Ave",
  "dateOfBirth": "2000-08-15",
  "registeredDate": "2026-07-18"
}