spring:
  application:
    name: patient-service
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

kafka:     
  topics:
    patient-event: patient.events        

server:
  port: 4000

logging:
  level:
    root: INFO

grpc:
  server:
    port: -1

billing:
  service:
    address: localhost
    grpc-port: 9001
    use-plaintext: true
    deadline-seconds: 3
  reconciliation:
    run-interval: 60s
    failed-max-attempts: 5
    failed-min-backoff: 1m
    failed-max-backoff: 30m